# ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gin-mall-ingress
spec:
  ingressClassName: nginx  # 必须指定！
  rules:
  - host: gin-mall.zzrr.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gin-mall-svc
            port:
              number: 80
